action = {
    0: 'Add',
    1: 'Update',
    2: 'Delete',
    3: 'Login',
    4: 'Logout',
}

resourcetype = {
    0: 'User',
    3: 'Media type',
    4: 'Host',
    5: 'Action',
    6: 'Graph',
    11: 'User group',
    13: 'Trigger',
    14: 'Host group',
    15: 'Item',
    16: 'Image',
    17: 'Value map',
    18: 'Service',
    19: 'Map',
    22: 'Web scenario',
    23: 'Discovery rule',
    25: 'Script',
    26: 'Proxy',
    27: 'Maintenance',
    28: 'Regular expression',
    29: 'Macro',
    30: 'Template',
    31: 'Trigger prototype',
    32: 'Icon mapping',
    33: 'Dashboard',
    34: 'Event correlation',
    35: 'Graph prototype',
    36: 'Item prototype',
    37: 'Host prototype',
    38: 'Autoregistration',
    39: 'Module',
    40: 'Settings',
    41: 'Housekeeping',
    42: 'Authentication',
    43: 'Template dashboard',
    44: 'User role',
    45: 'Auth token',
    46: 'Scheduled report',
    47: 'High availability node',
    48: 'SLA.',
}